export const PCM_SAMPLE_RATE_HZ = 16_000;
export const PCM_CHANNEL_COUNT = 1;
export const PCM_SAMPLE_BYTES = 2;
export const PCM_FRAME_DURATION_MS = 20;
export const PCM_SAMPLES_PER_FRAME = (PCM_SAMPLE_RATE_HZ / 1_000) * PCM_FRAME_DURATION_MS;
export const PCM_BYTES_PER_FRAME = PCM_SAMPLES_PER_FRAME * PCM_CHANNEL_COUNT * PCM_SAMPLE_BYTES;
